development:
  smtp_host: smtp.mandrillapp.com
  smtp_port: 587
  smtp_username: app33894328@heroku.com
  smtp_password: sr25L18DZEfYaRdWWUauDA
  cloud_name: hnf1yurqq
  cloud_api_key: 679539826725645
  cloud_api_secret: ru0lLttj9E9gOHAocz9b-6ydGCM
  secret_key_base: fe3eb92429490a2d55f68cf0bc3a2f1f1b177682ac1698f7482a0c4e94cdf79f10c09c128a9b7ad982638db7b8b59a1c17198ea67abef192db7b6590506d1720

test:
  smtp_host: smtp.mandrillapp.com
  smtp_port: 587
  smtp_username: app33894328@heroku.com
  smtp_password: sr25L18DZEfYaRdWWUauDA
  cloud_name: hnf1yurqq
  cloud_api_key: 679539826725645
  cloud_api_secret: ru0lLttj9E9gOHAocz9b-6ydGCM
  secret_key_base: fe3eb92429490a2d55f68cf0bc3a2f1f1b177682ac1698f7482a0c4e94cdf79f10c09c128a9b7ad982638db7b8b59a1c17198ea67abef192db7b6590506d1720

production:
  smtp_host: <%= ENV["SMTP_HOST"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  cloud_name: <%= ENV["CLOUD_NAME"] %>
  cloud_api_key: <%= ENV["CLOUD_API_KEY"] %>
  cloud_api_secret: <%= ENV["CLOUD_API_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>